import { suggestedAmbiguityOptions } from "../../lib/coachNotes";
import type { CoachNoteDraftV1, CoachNoteSection, EvidenceItem } from "../../lib/coachNotes";
import type { PriorCoachEvaluation } from "../../types/database";

export function PriorEvaluationsPanel({ evaluations }: { evaluations: PriorCoachEvaluation[] }) {
  return (
    <section className="card stack prior-eval-panel">
      <h2>Your prior evaluations for this athlete</h2>
      <p className="muted">
        Read-only context from your submitted evaluations. This is not merged into the current draft
        automatically.
      </p>
      {evaluations.map((evaluation) => (
        <details key={evaluation.id} className="prior-eval-item">
          <summary>
            {evaluation.campaignName} · {new Date(evaluation.submittedAt).toLocaleDateString()}
          </summary>
          {evaluation.strengths ? (
            <div>
              <strong>Strengths</strong>
              <p>{evaluation.strengths}</p>
            </div>
          ) : null}
          {evaluation.developmentAreas ? (
            <div>
              <strong>Development areas</strong>
              <p>{evaluation.developmentAreas}</p>
            </div>
          ) : null}
          {evaluation.overallNotes ? (
            <div>
              <strong>Overall notes</strong>
              <p>{evaluation.overallNotes}</p>
            </div>
          ) : null}
          {evaluation.recommendation ? (
            <p className="muted">
              Recommendation: {evaluation.recommendation.replaceAll("_", " ")}
            </p>
          ) : null}
        </details>
      ))}
    </section>
  );
}

export function CoachNoteCopilotPanel({
  draft,
  model,
  ambiguityCount,
  pendingClarifications,
  onPendingClarificationChange,
  onApplyClarifications,
  onRegenerateSection,
  regenerating,
}: {
  draft: CoachNoteDraftV1;
  model: string;
  ambiguityCount: number;
  pendingClarifications: Record<string, string>;
  onPendingClarificationChange: (sourceQuote: string, answer: string) => void;
  onApplyClarifications: () => void;
  onRegenerateSection: (section: CoachNoteSection) => void;
  regenerating: boolean;
}) {
  const groups: { label: string; items: EvidenceItem[]; section: CoachNoteSection }[] = [
    { label: "Strength evidence", items: draft.strengths, section: "strengths" },
    { label: "Development evidence", items: draft.developmentAreas, section: "development_areas" },
    {
      label: "Overall evidence",
      items: draft.overallObservations,
      section: "overall_observations",
    },
  ];
  return (
    <div className="stack">
      <p className="muted">
        Generated by {model}. Ambiguities flagged: {ambiguityCount}.
      </p>
      <details className="evidence-panel">
        <summary>Review grounding evidence</summary>
        {groups.map((group) =>
          group.items.length > 0 ? (
            <div key={group.label} className="evidence-group">
              <div className="section-title">
                <strong>{group.label}</strong>
                <button
                  type="button"
                  className="btn sm"
                  disabled={regenerating}
                  onClick={() => onRegenerateSection(group.section)}
                >
                  Regenerate section
                </button>
              </div>
              {group.items.map((item) => (
                <div
                  className="evidence-item"
                  key={`${group.label}-${item.draftText}-${item.evidenceQuotes.join("|")}`}
                >
                  <div>{item.draftText}</div>
                  <div className="muted">
                    Evidence: {item.evidenceQuotes.map((quote) => `"${quote}"`).join(", ")} (
                    {item.confidence})
                  </div>
                </div>
              ))}
            </div>
          ) : null,
        )}
      </details>
      {draft.ambiguities.length > 0 ? (
        <div className="clarification-panel stack">
          <strong>Needs coach clarification</strong>
          <p className="muted">
            Answer a clarification to re-structure the draft. This is not a chat.
          </p>
          {draft.ambiguities.map((ambiguity) => (
            <div
              className="clarification-card"
              key={`${ambiguity.sourceQuote}-${ambiguity.question}`}
            >
              <div>{ambiguity.question}</div>
              <div className="muted">Source: "{ambiguity.sourceQuote}"</div>
              <div className="btn-row">
                {suggestedAmbiguityOptions(ambiguity.sourceQuote).map((option) => (
                  <button
                    type="button"
                    className="btn sm"
                    key={option}
                    aria-pressed={pendingClarifications[ambiguity.sourceQuote] === option}
                    onClick={() => onPendingClarificationChange(ambiguity.sourceQuote, option)}
                  >
                    {option}
                  </button>
                ))}
              </div>
              <div className="field">
                <label htmlFor={`clarify-${ambiguity.sourceQuote}`}>Or type a short answer</label>
                <input
                  id={`clarify-${ambiguity.sourceQuote}`}
                  value={pendingClarifications[ambiguity.sourceQuote] ?? ""}
                  onChange={(event) =>
                    onPendingClarificationChange(ambiguity.sourceQuote, event.target.value)
                  }
                />
              </div>
            </div>
          ))}
          <button
            type="button"
            className="btn"
            disabled={regenerating}
            onClick={onApplyClarifications}
          >
            Apply clarifications and re-structure
          </button>
        </div>
      ) : null}
    </div>
  );
}
